version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  labels:
  - C-enhancement
  ignore:
  - dependency-name: core-foundation
    versions:
    - "> 0.6.4"
  - dependency-name: mach
    versions:
    - "> 0.2.3"
  - dependency-name: cbindgen
    versions:
    - 0.16.0
    - 0.17.0
    - 0.18.0
